### ISSUE TITLE
[BUG] Regression with `5.6.0`

### ISSUE THREAD

**Issue by toots** [ocsigen/js_of_ocaml#1558]
Sorry, I don't have a minimal reproduction setup but the js build of the liquidsoap parser has a regression with `js_of_ocaml` `5.6.0`:
```
Error while processing file ../liquidsoap/tests/language/eval.liq: Error: Unknown position:

Error -1: Exception raised: TypeError: sedlex_state_15 is not a function
```

The same build works with `5.5.2`..

**Comment by hhugo** [comment]
Can you try with master ?

**Comment by hhugo** [comment]
I wonder if this is the same issue as #1559 ? can you provide the problematic js file ?

**Comment by hhugo** [comment]
@toots, gentle ping ..

**Comment by toots** [comment]
Yes! It's here: https://www.dropbox.com/s/r72ued5rv0fd5a9/interactive_js.bc.js?dl=0

**Comment by hhugo** [comment]
Thanks, the issue is different from #1559.

Regression introduced by https://github.com/ocsigen/js_of_ocaml/pull/1544
Fixed by https://github.com/ocsigen/js_of_ocaml/pull/1541

Thanks for the report. I'll try to make a new release soon

**Comment by hhugo** [comment]
> It appears to be fixed if I install pinned version of this git repo's opam packages. This is a bit confusing, though, because the version is still reported as `5.5.2`..

I've just tried installing version 5.5.2 followed by a `opam pin add js_of_ocaml-compiler --dev` and I see `js_of_ocaml --version` report version correctly.
```
$ js_of_ocaml --version
5.6.0+git-5.6.0-30-gb7d29593db-dirty
```

`opam show js_of_ocaml-compiler` still reports `5.5.2` though. Is this the behavior you've witness ? or is it `js_of_ocaml --version` that was incorrect ?
