### ISSUE TITLE
Uncaught TypeError: a.hash is not a function

### ISSUE THREAD

**Issue by smondet** [ocsigen/js_of_ocaml#660]
A recent change seems to have started generating code that looks like

```js
if(a&&a.hash)b=b*fw+a.hash()|0}f(a);return b&cB}function
```

instead of this which didn't throw the exn:

```js
e=am(t.location.hash),w=bl(t.location.hash),x=am(t.location.href);n(C(abW),e,x,w);var
y=P(c(XO,e,0),abX)?n(nx,e,1,b(ny,e)-1|0):e,k=c(hJ,y,abY);if(k){var
q=k[2],a=k[1];if(i(a,abZ))if(i(a,ab0))if(i(a,ab1))if(i(a,ab2))if(i(a,ab3))if(i(a,ab4))var
```

for code like this:

```ocaml
      let frag = Dom_html.window ##. location ##. hash |> Js.to_string in
      let frag2 = Dom_html.window ##. location ##. hash |> Js.to_bytestring in
```

I'm reasonably confident that it worked at 3.0.1, and this appeared with the 3.1.0 upgrade.

Changing the `js_of_ocaml` version does not seem to influence it.
And `opam pin add js_of_ocaml-ppx 3.0.1` now fails with

```
#=== ERROR while compiling js_of_ocaml-ppx.3.0.1 ==============================#
# context              2.0.0~beta6 | linux/x86_64 | ocaml-base-compiler.4.05.0 | pinned(https://github.com/ocsigen/js_of_ocaml/archive/3.0.1.tar.gz)
# path                 ~/.opam/4.05.0/.opam-switch/build/js_of_ocaml-ppx.3.0.1
# command              ~/.opam/4.05.0/bin/jbuilder build -p js_of_ocaml-ppx -j 3
# exit-code            1
# env-file             ~/.opam/log/js_of_ocaml-ppx-20322-9b8556.env
# output-file          ~/.opam/log/js_of_ocaml-ppx-20322-9b8556.out
### output ###
      ocamlc ppx/ppx_deriving_json/lib/.ppx_deriving_json.objs/ppx_deriving_json.{cmi[...]
# (cd _build/default && /home/smondet/.opam/4.05.0/bin/ocamlc.opt -w -40 -g -bin-annot -I ppx/ppx_deriving_json/lib/.ppx_deriving_json.objs -I /home/smondet/.opam/4.05.0/lib/ocaml/compiler-libs -I /home/smondet/.opam/4.05.0/lib/ppx_deriving -I /home/smondet/.opam/4.05.0/lib/ppx_tools -I /home/smondet/.opam/4.05.0/lib/result -no-alias-deps -o ppx/ppx_deriving_json/lib/.ppx_deriving_json.objs/ppx[...]
# File "ppx/ppx_deriving_json/lib/ppx_deriving_json.pp.ml", line 2782, characters 41-42:
# Error: This expression has type
#          Parsetree.expression -> string -> Parsetree.expression
#        but an expression was expected of type
#          Parsetree.expression -> Ppx_deriving.tyvar -> Parsetree.expression
#        Type string is not compatible with type
#          Ppx_deriving.tyvar = string Location.loc 
    [...]
```

**Comment by vouillon** [comment]
The change was introduced by 5a86b3161c0b78417b99b4d2a464b24fcb6ac982.

Your issue is that you are calling `Hashtbl.hash` on a datastructure containing JavaScript objects with a property `hash` which is not a function. You should probably not do that, but the runtime system should check that `hash` is a function before calling it as well.

**Comment by smondet** [comment]
@vouillon where is the call to `Hashtbl.hash` supposed to be? there is none in my source

(Also it's `opam pin add js_oca_ocaml-compiler 3.0.1` that fixes/hides the issue)

**Comment by vouillon** [comment]
The piece of code you quote is in the hashing function. The change was indeed introduced between 3.0.1 and 3.0.1.

You could put a breakpoint right before `b=b*fw+a.hash()|0` or make the debugger stop on errors to see what is been hashed or to get  a stack trace.

**Comment by hhugo** [comment]
just pushed a fixed https://github.com/ocsigen/js_of_ocaml/commit/3b8b6b1604db2888f56ae529329a8129c9c99d9c
