### ISSUE TITLE
[BUG] installation error for version 2.7 on ocaml 4.02.3

### ISSUE THREAD

**Issue by bruce-ricard** [ocsigen/js_of_ocaml#1050]
**Describe the bug**

reproduction steps:
```
docker run -it ubuntu bash
apt update
apt install opam --yes
opam init --disable-sandboxing
eval $(opam env)
```
```
opam switch create 4.02.3
opam install js_of_ocaml.2.7
```
Output:
```
The following actions will be performed:
  - install js_of_ocaml 2.7

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[js_of_ocaml.2.7] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of js_of_ocaml failed at "/usr/bin/make build".

#=== ERROR while compiling js_of_ocaml.2.7 ====================================#
# context     2.0.5 | linux/x86_64 | ocaml-base-compiler.4.02.3 | https://opam.ocaml.org#f4d79830
# path        ~/.opam/4.02.3/.opam-switch/build/js_of_ocaml.2.7
# command     /usr/bin/make build
# exit-code   2
# env-file    ~/.opam/log/js_of_ocaml-26911-d2c37b.env
# output-file ~/.opam/log/js_of_ocaml-26911-d2c37b.out
### output ###
# [...]
# ocamlfind ocamlopt -w +A-4-7-9-37-38-41-44-45 -I +compiler-libs -safe-string -package cmdliner -package base64 -package findlib -for-pack Compiler -g -c js_token.ml
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /root/.opam/4.02.3/lib/ocaml, /root/.opam/4.02.3/lib/ocaml/compiler-libs
# menhir --infer --external-tokens Js_token --explain js_parser.mly
# Warning: 12 states have shift/reduce conflicts.
# Warning: 47 shift/reduce conflicts were arbitrarily resolved.
# ocamlfind ocamlc     -w +A-4-7-9-37-38-41-44-45 -I +compiler-libs -safe-string -package cmdliner -package base64 -package findlib -c js_parser.mli
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /root/.opam/4.02.3/lib/ocaml, /root/.opam/4.02.3/lib/ocaml/compiler-libs
# File "js_parser.mli", line 12, characters 73-85:
# Error: Unbound module J
# make[1]: *** [Makefile:114: js_parser.cmi] Error 2
# make[1]: Leaving directory /root/.opam/4.02.3/.opam-switch/build/js_of_ocaml.2.7/compiler
# make: *** [Makefile:13: compiler] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build js_of_ocaml 2.7
+-
```

**Expected behavior**
It installs successfully 

**Versions**
ocaml switch: 4.02.3
js_of_ocaml: 2.7

I want to upgrade to eliom 6 but I haven't had the time yet... so I'm stuck with that 🙄 

I used to work with that setup (ocaml 4.02.3 & eliom 5), I probably tried last time about 2 years ago... So I'm pretty sure it used to work. I have an old docker image with these versions successfully installed.

I confirmed that I can install the latest version:
```
-> installed js_of_ocaml.3.7.0
```

update: I also confirmed that I can install it on the older `ubuntu:18.04` image

```
docker run -it ubuntu:18.04 bash
apt update
apt install opam
opam init
opam switch 4.02.3
opam depext conf-m4.1
opam install js_of_ocaml.2.7
```
is successful. 

update: After upgrading opam to 2.0.7 on the ubuntu:18.04 image, I'm getting the same error again. So it appears that eliom 2 does something that breaks the installation of js_of_ocaml 2.7 -> 2.8.4

update: I installed opam 1.2.2 on osx, used the 4.02.3 switch and get the same error again when running `opam install js_of_ocaml.2.8.4`. I guess it's actually not an opam issue. 🤷 

update: I reran the install command and somehow now it's installed 🤔 . No idea what is going on.

**Comment by dbuenzli** [comment]
Do you really need 2.7 ? Maybe the build of more recent versions is better tested.

**Comment by bruce-ricard** [comment]
Getting a different error on the latest ocaml switch:

```
opam switch create 4.10.0
opam install js_of_ocaml.2.7 --debug
```

```
opam install js_of_ocaml.2.7 --debug
[WARNING] Running as root is not recommended
00:00.004  GSTATE                 LOAD-GLOBAL-STATE @ /root/.opam
00:00.004  RSTATE                 LOAD-REPOSITORY-STATE @ /root/.opam
00:00.093  RSTATE                 Loaded /root/.opam/repo/state.cache in 0.089s
00:00.170  RSTATE                 Cache found
00:00.170  STATE                  LOAD-SWITCH-STATE @ 4.10.0
00:00.211  STATE                  Detected changed packages (marked for reinstall): {}
00:00.211  STATE                  Switch state loaded in 0.041s
00:00.211  FILE(switch-state)     Wrote /root/.opam/4.10.0/.opam-switch/backup/state-20200809190431.export in 0.000s
00:00.303  CLIENT                 INSTALL js_of_ocaml.2.7
00:00.511  SYSTEM                 [log-36527-ccabea] (in 0.009s) ocamlc -vnum
00:00.630  CLIENT                 Orphans: (changes: { js_of_ocaml.2.7 }, transitive: false) -> full {}, versions {}
00:00.897  SOLVER                 resolve request=install:(js_of_ocaml (= 2.7)) remove:() upgrade:()
00:01.699  SOLVER                 Load cudf universe (depopts:false, build:true, post:true)
00:01.785  CUDF                   resolve request=install:(js%5fof%5focaml (= 15)) remove:() upgrade:()
00:01.785  SOLVER                 Calling solver builtin-mccs+glpk with criteria -removed,-count[version-lag,request],-count[version-lag,changed],-changed
00:02.499  CUDF                   Solver call done in 0.715
00:03.062  CLIENT                 conflict!
Sorry, no solution found: there seems to be a problem with your request.
```

**Comment by bruce-ricard** [comment]
> Do you really need 2.7 ? Maybe the build of more recent versions is better tested.

@dbuenzli as mentioned above, I am currently stuck on Eliom 5 which requires js_of_ocaml 2.7.

**Comment by dbuenzli** [comment]
@bruce-ricard. Sorry I missed that. You won't be able to use a later OCaml thought: 

```
> opam info js_of_ocaml.2.7 | grep depends
depends:      "ocaml" {>= "4.00.0" & < "4.03.0"}
```

**Comment by bruce-ricard** [comment]
Good catch. The error message isn't as helpful as it could be.

**Comment by dbuenzli** [comment]
Btw. there are a few other js_of_ocaml version you could try it seems eliom.5.0.0 has the constraint:
```
"js_of_ocaml" {> "2.6" & < "3.0"}
```
So this leaves you with `2.6  2.7  2.8  2.8.1  2.8.2  2.8.3  2.8.4` to test.

**Comment by bruce-ricard** [comment]
Getting the same error message with `2.8` 😢

**Comment by dbuenzli** [comment]
Are you sure your opam packages are up-to-date ? Here (on macos but that shouldn't matter) the following succeeded: 
```
opam update 
opam switch 4.03.0 
opam install js_of_ocaml.2.8.4
```

**Comment by bruce-ricard** [comment]
I am not using the `4.03.0` switch but the `4.02.3`. I remember that eliom 5 needs ocaml 4.02.3, even though it's not in the `opam info`.

**Comment by bruce-ricard** [comment]
I just tried doing the same thing using the `ubuntu:18.04` image and it succeeds. It happens to come with the "old" `opam`, so I don't know if the problem comes from the Ubuntu version or the opam version.

**Comment by bruce-ricard** [comment]
After upgrading `opam` to `2.0.7` on the `ubuntu:18.04` image, I'm getting the same error again. So it appears that eliom 2 does something that breaks the installation of `js_of_ocaml 2.7 -> 2.8.4`

**Comment by bruce-ricard** [comment]
> Are you sure your opam packages are up-to-date ? Here (on macos but that shouldn't matter) the following succeeded:
> 
> ```
> opam update 
> opam switch 4.03.0 
> opam install js_of_ocaml.2.8.4
> ```

That is interesting though, I tried using the `4.03.0` switch and I wasn't able to install js_of_ocaml. 

Running `opam update` returns 
> [default] no changes from https://opam.ocaml.org

**Comment by bruce-ricard** [comment]
> Btw. there are a few other js_of_ocaml version you could try it seems eliom.5.0.0 has the constraint:
> 
> ```
> "js_of_ocaml" {> "2.6" & < "3.0"}
> ```
> 
> So this leaves you with `2.7 2.8 2.8.1 2.8.2 2.8.3 2.8.4` to test.

That is actually somehow not correct.
I installed js_of_ocaml 2.8.4 manually, and then installed eliom 5.0.0, it downgraded js_of_ocaml to 2.7.
When I now try to upgrade back to 2.8.4, it says that it would have to upgrade eliom to v6. 

There appears to have some mistakes in the version requirements.

**Comment by hhugo** [comment]
I was able to install eliom.5 with js_of_ocaml.2.7 without any issue.
- Do you have any package pinned (`opam pin`) ?
- what version of menhir do you use (`menhir --version`) ?

The generated js_parser.mli I get doesn't reference a module `J` at all. It looks like the menhir invocation on your side generate something different.  

```shell
cat compiler/js_parser.mli
```
```ocaml
(* The type of tokens. *)

type token = Js_token.token

(* This exception is raised by the monolithic API functions. *)

exception Error

(* The monolithic API. *)

val standalone_expression: (Lexing.lexbuf -> token) -> Lexing.lexbuf -> (Javascript.expression)

val program: (Lexing.lexbuf -> token) -> Lexing.lexbuf -> (Javascript.program)
```

**Comment by hhugo** [comment]
eliom 5 will force js_of_ocaml 2.7 because of tyxml.
eliom 5 requires tyxml.3.6
js_of_ocaml.2.8.* in incompatible with tyxml < 4

**Comment by bruce-ricard** [comment]
@hhugo did you try it in the latest ubuntu docker container?

I don't have any package pinned, I have the default version of menhir that comes when I 'apt install opam'. So that means no menhir, it's not installed.

**Comment by hhugo** [comment]
I have

```
$ menhir --version
menhir, version 20190924
```

This might be related.

**Comment by hhugo** [comment]
Indeed, I can reproduce the error with `menhir.20200624`.
menhir infers js_parser.mli as  
```shell
$ cat js_parser.mli 
```
```ocaml
(* The type of tokens. *)

type token = Js_token.token

(* This exception is raised by the monolithic API functions. *)

exception Error

(* The monolithic API. *)

val standalone_expression: (Lexing.lexbuf -> token) -> Lexing.lexbuf -> (J.expression)

val program: (Lexing.lexbuf -> token) -> Lexing.lexbuf -> (Javascript.program)
```
The module `J` is only know in the implementation, not in the interface.

You might want to report this issue in menhir https://gitlab.inria.fr/fpottier/menhir/-/issues
cc @fpottier

**Comment by bruce-ricard** [comment]
Wouldn't the main issue be that js_of_ocaml 2.7 has the wrong version of menhir set in its opam configuration file?

**Comment by fpottier** [comment]
Hello!

The problem is caused by the module alias `module J = Javascript` at line 12 of `js_parser.mly`. The recommended fix is to remove this declaration.

Beginning with Menhir 20200525, Menhir prefers to use the types inferred by the OCaml compiler over the types provided by the user in `%type` declarations. (This may sound strange, but it is actually required for soundness in some cases.) In the presence of a module alias like this, OCaml can infer types that begin with `J.` instead of `Javascript.`, and Menhir does not detect that `J` is a local name.

**Comment by hhugo** [comment]
Ok.
Jsoo stopped relying on `--infer` starting with `js_of_ocaml.3.0`. We can add a version constraint on menhir for older jsoo versions.

**Comment by hhugo** [comment]
I've added constraints on the `2.*` versions. The issue should automatically be resolved once the opam-repository PR is merged and after you `opam update`
