### ISSUE TITLE
Graphics_js issue on 3.12

### ISSUE THREAD

**Issue by Drup** [ocsigen/js_of_ocaml#166]
For some reason, `Graphics_js` doesn't work under ocaml 3.12, see [this log](https://travis-ci.org/Drup/LILiS/builds/25426634) for the log under the various ocaml version. 
The error is just 

```
Error: Unbound module Graphics_js
```

The build on travis is using js_of_ocaml 2.2, but it's reproducible on master.

Hoping I'm not missing something obvious here.
